In [10]:
import numpy as np
import pandas as pd

RANK_CHARS = '23456789TJQKA'
SUIT_CHARS = 'cdhs'
def card_str(c): return RANK_CHARS[int(c)>>2] + SUIT_CHARS[int(c)&3]
def board_str(row): return ' '.join(card_str(row[i]) for i in range(4))

## Raw Data (Golden Source)

In [11]:
meta = np.load('raw_training_data/meta.npy')
ranges = np.load('raw_training_data/ranges.npy')
values = np.load('raw_training_data/values.npy')

reach_oop = ranges[:, :1326]
reach_ip  = ranges[:, 1326:]
cfv_oop   = values[:, :1326]
cfv_ip    = values[:, 1326:]

oop_total = reach_oop.sum(axis=1)
ip_total  = reach_ip.sum(axis=1)

df_raw = pd.DataFrame({
    'board': [board_str(meta[i]) for i in range(len(meta))],
    'pot': meta[:, 4].astype(int),
    'stack': meta[:, 5].astype(int),
    'spr': np.round(meta[:, 5] / meta[:, 4], 1),
    'oop_combos': (reach_oop > 0).sum(axis=1),
    'ip_combos': (reach_ip > 0).sum(axis=1),
    'oop_mean_cfv': np.round(np.where(oop_total > 0, (cfv_oop * reach_oop).sum(axis=1) / oop_total, 0), 4),
    'ip_mean_cfv': np.round(np.where(ip_total > 0, (cfv_ip * reach_ip).sum(axis=1) / ip_total, 0), 4),
})

print(f'Raw: meta{meta.shape}  ranges{ranges.shape}  values{values.shape}')
print(f'Storage: {sum(x.nbytes for x in [meta,ranges,values])/1e6:.1f} MB')
df_raw

Raw: meta(50, 6)  ranges(50, 2652)  values(50, 2652)
Storage: 1.1 MB

,board,pot,stack,spr,oop_combos,ip_combos,oop_mean_cfv,ip_mean_cfv
0,2s 5d 6c Td,3200,3500,1.1,1128,1128,-0.4816,0.4816
1,7d Js Qh 9c,2800,2400,0.9,1128,1128,0.3213,-0.3213
2,8c 8s Qs 8d,5400,4300,0.8,1128,1128,0.0753,-0.0753
3,4s Jd Ah Js,3600,9700,2.7,1128,1128,0.3980,-0.3980
4,5h 5s 8c 6d,5000,8800,1.8,1128,1128,-0.0343,0.0343
5,8h Td Qc Jh,5500,1100,0.2,1128,1128,-0.1610,0.1610
6,2d 5h 7s 7c,3100,7200,2.3,1128,1128,-0.1993,0.1993
7,2h 7d As 8c,1400,9900,7.1,1128,1128,-0.1486,0.1486
8,2h 5c Th 3s,1200,5600,4.7,1128,1128,0.0135,-0.0135
9,2d 6h Ad 8h,1800,9000,5.0,1128,1128,-0.4750,0.4750
10,5d 8h 9h Td,5800,2600,0.4,1128,1128,-0.2927,0.2927
11,3s 4c 7s As,2500,8500,3.4,1128,1128,0.3451,-0.3451
12,4s 8h Qc 9c,3100,3300,1.1,1128,1128,-0.0073,0.0073
13,2c 5c Qd 7h,1200,4900,4.1,1128,1128,0.4425,-0.4425
14,7c 8s 9h Ts,2700,6100,2.3,1128,1128,-0.4664,0.4664
15,4s 6h 6s 6c,800,4200,5.2,1128,1128,-0.4812,0.4812
16,6s 8h Ks 8s,3600,10000,2.8,1128,1128,-0.3842,0.3842
17,4s 8c Qs 2c,4000,2300,0.6,1128,1128,0.2768,-0.2768
18,4h Jh Kh 5h,3100,4900,1.6,1128,1128,0.3132,-0.3132
19,6c 8h Kh 5h,3100,9500,3.1,1128,1128,-0.4931,0.4931
20,4c Jc As 5d,3100,1100,0.4,1128,1128,-0.4640,0.4640
21,5c Js As 7c,1000,2200,2.2,1128,1128,-0.1933,0.1933
22,4c 6h 9s 7h,1900,1100,0.6,1128,1128,0.0335,-0.0335
23,6s 9c Kc Qs,5200,2900,0.6,1128,1128,-0.0662,0.0662
24,4d 7s Qs Jh,6000,5500,0.9,1128,1128,0.1508,-0.1508
25,4s 6c As 2s,2000,7600,3.8,1128,1128,-0.1407,0.1407
26,4s Jd Qc Jc,2200,1300,0.6,1128,1128,-0.0641,0.0641
27,2s 7d Kh Ts,500,4400,8.8,1128,1128,-0.1881,0.1881
28,4h Qh Ks Qc,5700,7900,1.4,1128,1128,-0.1662,0.1662
29,8h Jd Kh Js,6000,5700,1.0,1128,1128,0.2818,-0.2818
30,8c Ks Ad 5c,3900,5700,1.5,1128,1128,-0.2383,0.2383
31,2h 5h 6d 2d,1900,9300,4.9,1128,1128,0.3685,-0.3685
32,4d 7c Jd Td,4400,6500,1.5,1128,1128,-0.2276,0.2276
33,2s 4s 9h Kh,1200,8300,6.9,1128,1128,0.1748,-0.1748
34,2c Ts Jh Qs,3900,2400,0.6,1128,1128,0.1224,-0.1224
35,2d 7s 8d As,4300,9700,2.3,1128,1128,0.3124,-0.3124
36,6c 9d Jh 6h,5000,5000,1.0,1128,1128,-0.1809,0.1809
37,2s 6s Tc 7s,2500,8300,3.3,1128,1128,0.3858,-0.3858
38,4s 8c Qc 9h,5000,5400,1.1,1128,1128,-0.1327,0.1327
39,3h 3s 4s 9s,5500,6600,1.2,1128,1128,0.0773,-0.0773
40,6h 8c Qs Qd,5600,1200,0.2,1128,1128,-0.0338,0.0338
41,2h 3h 4c 9c,900,7800,8.7,1128,1128,-0.1638,0.1638
42,4h 5s Ad 7h,1700,1700,1.0,1128,1128,0.4839,-0.4839
43,5s 9s Tc Kd,3000,9700,3.2,1128,1128,0.3151,-0.3151
44,4s 5c 6c 4c,2200,3900,1.8,1128,1128,0.1445,-0.1445
45,2s 8s Qs Ks,2500,7700,3.1,1128,1128,-0.4717,0.4717
46,3d 4h 8d Tc,4300,9500,2.2,1128,1128,0.1553,-0.1553
47,Js Ac Ad 8h,4100,6500,1.6,1128,1128,0.4104,-0.4104
48,3s 7d 9d 8s,2800,6500,2.3,1128,1128,0.4707,-0.4707
49,9s Js Kh 3c,4800,5000,1.0,1128,1128,0.0381,-0.0381

## Bucketed Data (projected from raw)

In [12]:
inputs  = np.load('projected_training_data/inputs.npy')
targets = np.load('projected_training_data/targets.npy')

K = 1000
board_feat     = inputs[:, :15]
range_oop_buck = inputs[:, 15:15+K]
range_ip_buck  = inputs[:, 15+K:]
cfv_oop_buck   = targets[:, :K]
cfv_ip_buck    = targets[:, K:]

feat_names = ['r1','r2','r3','r4','suit_c','suit_d','suit_h','suit_s',
              'paired','trips','mono','connect','log_spr','pot_frac','stk_frac']

df_buck = pd.DataFrame({
    'board': [board_str(meta[i]) for i in range(len(meta))],
    'oop_active_buckets': (range_oop_buck > 0).sum(axis=1),
    'ip_active_buckets': (range_ip_buck > 0).sum(axis=1),
    'oop_mean_cfv_buck': np.round(cfv_oop_buck.mean(axis=1), 4),
    'ip_mean_cfv_buck': np.round(cfv_ip_buck.mean(axis=1), 4),
})

print(f'Bucketed: inputs{inputs.shape}  targets{targets.shape}')
print(f'Storage: {sum(x.nbytes for x in [inputs,targets])/1e6:.1f} MB')
df_buck

Bucketed: inputs(50, 2015)  targets(50, 2000)
Storage: 0.8 MB

,board,oop_active_buckets,ip_active_buckets,oop_mean_cfv_buck,ip_mean_cfv_buck
0,2s 5d 6c Td,809,809,-0.0237,0.3830
1,7d Js Qh 9c,169,169,0.0299,-0.0446
2,8c 8s Qs 8d,705,705,0.3899,0.3024
3,4s Jd Ah Js,754,754,0.2402,0.0546
4,5h 5s 8c 6d,169,169,0.0428,0.0444
5,8h Td Qc Jh,749,749,-0.0316,0.1041
6,2d 5h 7s 7c,169,169,0.0660,0.0805
7,2h 7d As 8c,169,169,0.0326,0.0426
8,2h 5c Th 3s,785,785,0.0815,0.2867
9,2d 6h Ad 8h,722,722,-0.2137,0.3157
10,5d 8h 9h Td,599,599,0.0307,0.1619
11,3s 4c 7s As,686,686,0.0161,-0.1435
12,4s 8h Qc 9c,754,754,0.0568,0.0882
13,2c 5c Qd 7h,754,754,0.2499,-0.2025
14,7c 8s 9h Ts,765,765,-0.1612,0.3278
15,4s 6h 6s 6c,720,720,-0.2131,0.3311
16,6s 8h Ks 8s,686,686,0.2293,0.3196
17,4s 8c Qs 2c,611,611,-0.0054,-0.1846
18,4h Jh Kh 5h,344,344,0.0536,-0.0785
19,6c 8h Kh 5h,709,709,-0.1615,0.3331
20,4c Jc As 5d,765,765,-0.2010,0.3067
21,5c Js As 7c,647,647,0.0664,0.2128
22,4c 6h 9s 7h,788,788,-0.0889,-0.0056
23,6s 9c Kc Qs,591,591,-0.0374,-0.0189
24,4d 7s Qs Jh,754,754,0.0178,-0.0181
25,4s 6c As 2s,686,686,0.2047,0.3542
26,4s Jd Qc Jc,765,765,0.2113,0.1900
27,2s 7d Kh Ts,754,754,0.1740,0.2106
28,4h Qh Ks Qc,796,796,-0.1920,0.0682
29,8h Jd Kh Js,721,721,0.1611,-0.0746
30,8c Ks Ad 5c,765,765,0.1282,0.2813
31,2h 5h 6d 2d,551,551,0.1788,0.0711
32,4d 7c Jd Td,686,686,0.0316,0.1304
33,2s 4s 9h Kh,652,652,0.1115,0.0939
34,2c Ts Jh Qs,765,765,-0.0798,-0.1065
35,2d 7s 8d As,670,670,0.1815,0.0302
36,6c 9d Jh 6h,754,754,0.0713,0.2433
37,2s 6s Tc 7s,686,686,0.1526,-0.2672
38,4s 8c Qc 9h,754,754,-0.0194,0.0982
39,3h 3s 4s 9s,686,686,0.3274,0.2543
40,6h 8c Qs Qd,169,169,-0.0305,-0.0248
41,2h 3h 4c 9c,628,628,0.1724,0.2355
42,4h 5s Ad 7h,795,795,0.3640,-0.1106
43,5s 9s Tc Kd,754,754,0.2453,-0.0034
44,4s 5c 6c 4c,686,686,0.0300,-0.0313
45,2s 8s Qs Ks,322,322,0.0810,0.1528
46,3d 4h 8d Tc,792,792,0.0786,-0.0242
47,Js Ac Ad 8h,169,169,0.0674,0.0035
48,3s 7d 9d 8s,611,611,0.2539,-0.0484
49,9s Js Kh 3c,765,765,0.0857,0.0981

## Board Features (15-dim)

In [13]:
df_feat = pd.DataFrame(np.round(board_feat, 3), columns=feat_names)
df_feat.insert(0, 'board', [board_str(meta[i]) for i in range(len(meta))])
df_feat

,board,r1,r2,r3,r4,suit_c,suit_d,suit_h,suit_s,paired,trips,mono,connect,log_spr,pot_frac,stk_frac
0,2s 5d 6c Td,0.667,0.333,0.250,0.000,0.25,0.50,0.00,0.25,0.0,0.0,0.0,0.333,0.239,0.478,0.522
1,7d Js Qh 9c,0.833,0.750,0.583,0.417,0.25,0.25,0.25,0.25,0.0,0.0,0.0,0.583,0.200,0.538,0.462
2,8c 8s Qs 8d,0.833,0.500,0.500,0.500,0.25,0.25,0.00,0.50,1.0,1.0,0.0,0.667,0.189,0.557,0.443
3,4s Jd Ah Js,1.000,0.750,0.750,0.167,0.00,0.25,0.25,0.50,1.0,0.0,0.0,0.167,0.423,0.271,0.729
4,5h 5s 8c 6d,0.500,0.333,0.250,0.250,0.25,0.25,0.25,0.25,1.0,0.0,0.0,0.750,0.328,0.362,0.638
5,8h Td Qc Jh,0.833,0.750,0.667,0.500,0.25,0.25,0.50,0.00,0.0,0.0,0.0,0.667,0.059,0.833,0.167
6,2d 5h 7s 7c,0.417,0.417,0.250,0.000,0.25,0.25,0.25,0.25,1.0,0.0,0.0,0.583,0.388,0.301,0.699
7,2h 7d As 8c,1.000,0.500,0.417,0.000,0.25,0.25,0.25,0.25,0.0,0.0,0.0,0.000,0.676,0.124,0.876
8,2h 5c Th 3s,0.667,0.250,0.083,0.000,0.25,0.00,0.50,0.25,0.0,0.0,0.0,0.333,0.561,0.176,0.824
9,2d 6h Ad 8h,1.000,0.500,0.333,0.000,0.00,0.50,0.50,0.00,0.0,0.0,0.0,0.000,0.580,0.167,0.833
10,5d 8h 9h Td,0.667,0.583,0.500,0.250,0.00,0.50,0.50,0.00,0.0,0.0,0.0,0.583,0.120,0.690,0.310
11,3s 4c 7s As,1.000,0.417,0.167,0.083,0.25,0.00,0.00,0.75,0.0,0.0,1.0,0.083,0.479,0.227,0.773
12,4s 8h Qc 9c,0.833,0.583,0.500,0.167,0.50,0.00,0.25,0.25,0.0,0.0,0.0,0.333,0.235,0.484,0.516
13,2c 5c Qd 7h,0.833,0.417,0.250,0.000,0.50,0.25,0.25,0.00,0.0,0.0,0.0,0.167,0.526,0.197,0.803
14,7c 8s 9h Ts,0.667,0.583,0.500,0.417,0.25,0.00,0.25,0.50,0.0,0.0,0.0,0.750,0.382,0.307,0.693
15,4s 6h 6s 6c,0.333,0.333,0.333,0.167,0.25,0.00,0.25,0.50,1.0,1.0,0.0,0.833,0.593,0.160,0.840
16,6s 8h Ks 8s,0.917,0.500,0.500,0.333,0.00,0.00,0.25,0.75,1.0,0.0,1.0,0.417,0.430,0.265,0.735
17,4s 8c Qs 2c,0.833,0.500,0.167,0.000,0.50,0.00,0.00,0.50,0.0,0.0,0.0,0.167,0.147,0.635,0.365
18,4h Jh Kh 5h,0.917,0.750,0.250,0.167,0.00,0.00,1.00,0.00,0.0,0.0,1.0,0.250,0.307,0.388,0.612
19,6c 8h Kh 5h,0.917,0.500,0.333,0.250,0.25,0.00,0.75,0.00,0.0,0.0,1.0,0.333,0.454,0.246,0.754
20,4c Jc As 5d,1.000,0.750,0.250,0.167,0.50,0.25,0.00,0.25,0.0,0.0,0.0,0.167,0.098,0.738,0.262
21,5c Js As 7c,1.000,0.750,0.417,0.250,0.50,0.00,0.00,0.50,0.0,0.0,0.0,0.250,0.376,0.312,0.688
22,4c 6h 9s 7h,0.583,0.417,0.333,0.167,0.25,0.00,0.50,0.25,0.0,0.0,0.0,0.583,0.148,0.633,0.367
23,6s 9c Kc Qs,0.917,0.833,0.583,0.333,0.50,0.00,0.00,0.50,0.0,0.0,0.0,0.417,0.143,0.642,0.358
24,4d 7s Qs Jh,0.833,0.750,0.417,0.167,0.00,0.25,0.25,0.50,0.0,0.0,0.0,0.333,0.210,0.522,0.478
25,4s 6c As 2s,1.000,0.333,0.167,0.000,0.25,0.00,0.00,0.75,0.0,0.0,1.0,0.000,0.507,0.208,0.792
26,4s Jd Qc Jc,0.833,0.750,0.750,0.167,0.50,0.25,0.00,0.25,1.0,0.0,0.0,0.333,0.150,0.629,0.371
27,2s 7d Kh Ts,0.917,0.667,0.417,0.000,0.00,0.25,0.25,0.50,0.0,0.0,0.0,0.083,0.738,0.102,0.898
28,4h Qh Ks Qc,0.917,0.833,0.833,0.167,0.25,0.00,0.50,0.25,1.0,0.0,0.0,0.250,0.281,0.419,0.581
29,8h Jd Kh Js,0.917,0.750,0.750,0.500,0.00,0.25,0.50,0.25,1.0,0.0,0.0,0.583,0.216,0.513,0.487
30,8c Ks Ad 5c,1.000,0.917,0.500,0.250,0.50,0.25,0.00,0.25,0.0,0.0,0.0,0.250,0.291,0.406,0.594
31,2h 5h 6d 2d,0.333,0.250,0.000,0.000,0.00,0.50,0.50,0.00,1.0,0.0,0.0,0.667,0.574,0.170,0.830
32,4d 7c Jd Td,0.750,0.667,0.417,0.167,0.25,0.75,0.00,0.00,0.0,0.0,1.0,0.417,0.293,0.404,0.596
33,2s 4s 9h Kh,0.917,0.583,0.167,0.000,0.00,0.00,0.50,0.50,0.0,0.0,0.0,0.083,0.669,0.126,0.874
34,2c Ts Jh Qs,0.833,0.750,0.667,0.000,0.25,0.00,0.25,0.50,0.0,0.0,0.0,0.167,0.155,0.619,0.381
35,2d 7s 8d As,1.000,0.500,0.417,0.000,0.00,0.50,0.00,0.50,0.0,0.0,0.0,0.000,0.382,0.307,0.693
36,6c 9d Jh 6h,0.750,0.583,0.333,0.333,0.25,0.25,0.50,0.00,1.0,0.0,0.0,0.583,0.224,0.500,0.500
37,2s 6s Tc 7s,0.667,0.417,0.333,0.000,0.25,0.00,0.00,0.75,0.0,0.0,1.0,0.333,0.473,0.231,0.769
38,4s 8c Qc 9h,0.833,0.583,0.500,0.167,0.50,0.00,0.25,0.25,0.0,0.0,0.0,0.333,0.237,0.481,0.519
39,3h 3s 4s 9s,0.583,0.167,0.083,0.083,0.00,0.00,0.25,0.75,1.0,0.0,1.0,0.500,0.255,0.455,0.545
40,6h 8c Qs Qd,0.833,0.833,0.500,0.333,0.25,0.25,0.25,0.25,1.0,0.0,0.0,0.500,0.063,0.824,0.176
41,2h 3h 4c 9c,0.583,0.167,0.083,0.000,0.50,0.00,0.50,0.00,0.0,0.0,0.0,0.417,0.734,0.103,0.897
42,4h 5s Ad 7h,1.000,0.417,0.250,0.167,0.00,0.25,0.50,0.25,0.0,0.0,0.0,0.167,0.224,0.500,0.500
43,5s 9s Tc Kd,0.917,0.667,0.583,0.250,0.25,0.25,0.00,0.50,0.0,0.0,0.0,0.333,0.467,0.236,0.764
44,4s 5c 6c 4c,0.333,0.250,0.167,0.167,0.75,0.00,0.00,0.25,1.0,0.0,1.0,0.833,0.330,0.361,0.639
45,2s 8s Qs Ks,0.917,0.833,0.500,0.000,0.00,0.00,0.00,1.00,0.0,0.0,1.0,0.083,0.455,0.245,0.755
46,3d 4h 8d Tc,0.667,0.500,0.167,0.083,0.25,0.50,0.25,0.00,0.0,0.0,0.0,0.417,0.377,0.312,0.688
47,Js Ac Ad 8h,1.000,1.000,0.750,0.500,0.25,0.25,0.25,0.25,1.0,0.0,0.0,0.500,0.307,0.387,0.613
48,3s 7d 9d 8s,0.583,0.500,0.417,0.083,0.00,0.50,0.00,0.50,0.0,0.0,0.0,0.500,0.388,0.301,0.699
49,9s Js Kh 3c,0.917,0.750,0.583,0.083,0.25,0.00,0.25,0.50,0.0,0.0,0.0,0.167,0.231,0.490,0.510